/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiCalendarRouteImport } from './routes/api.calendar'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiConversationsRouteImport } from './routes/api.conversations'
import { Route as ApiDocumentSearchRouteImport } from './routes/api.document-search'
import { Route as ApiDocumentsRouteImport } from './routes/api.documents'
import { Route as ApiInternetRouteImport } from './routes/api.internet'
import { Route as ApiMemoriesRouteImport } from './routes/api.memories'
import { Route as ApiModelSettingsRouteImport } from './routes/api.model-settings'
import { Route as ApiModelsRouteImport } from './routes/api.models'
import { Route as ApiSystemRouteImport } from './routes/api.system'
import { Route as ApiConversationsIdRouteImport } from './routes/api.conversations.$id'
import { Route as ApiMemoriesIdRouteImport } from './routes/api.memories.$id'
import { Route as ApiModelsPullRouteImport } from './routes/api.models.pull'
import { Route as ApiConversationsIdDocumentsRouteImport } from './routes/api.conversations.$id.documents'
import { Route as ApiConversationsIdDocumentsDocumentIdRouteImport } from './routes/api.conversations.$id.documents.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentSearchRoute = ApiDocumentSearchRouteImport.update({
  id: '/api/document-search',
  path: '/api/document-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternetRoute = ApiInternetRouteImport.update({
  id: '/api/internet',
  path: '/api/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesRoute = ApiMemoriesRouteImport.update({
  id: '/api/memories',
  path: '/api/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelSettingsRoute = ApiModelSettingsRouteImport.update({
  id: '/api/model-settings',
  path: '/api/model-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemRoute = ApiSystemRouteImport.update({
  id: '/api/system',
  path: '/api/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConversationsRoute,
} as any)
const ApiMemoriesIdRoute = ApiMemoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMemoriesRoute,
} as any)
const ApiModelsPullRoute = ApiModelsPullRouteImport.update({
  id: '/pull',
  path: '/pull',
  getParentRoute: () => ApiModelsRoute,
} as any)
const ApiConversationsIdDocumentsRoute =
  ApiConversationsIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApiConversationsIdRoute,
  } as any)
const ApiConversationsIdDocumentsDocumentIdRoute =
  ApiConversationsIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ApiConversationsIdDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/document-search': typeof ApiDocumentSearchRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/internet': typeof ApiInternetRoute
  '/api/memories': typeof ApiMemoriesRouteWithChildren
  '/api/model-settings': typeof ApiModelSettingsRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/system': typeof ApiSystemRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/memories/$id': typeof ApiMemoriesIdRoute
  '/api/models/pull': typeof ApiModelsPullRoute
  '/api/conversations/$id/documents': typeof ApiConversationsIdDocumentsRouteWithChildren
  '/api/conversations/$id/documents/$documentId': typeof ApiConversationsIdDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/document-search': typeof ApiDocumentSearchRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/internet': typeof ApiInternetRoute
  '/api/memories': typeof ApiMemoriesRouteWithChildren
  '/api/model-settings': typeof ApiModelSettingsRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/system': typeof ApiSystemRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/memories/$id': typeof ApiMemoriesIdRoute
  '/api/models/pull': typeof ApiModelsPullRoute
  '/api/conversations/$id/documents': typeof ApiConversationsIdDocumentsRouteWithChildren
  '/api/conversations/$id/documents/$documentId': typeof ApiConversationsIdDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/document-search': typeof ApiDocumentSearchRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/internet': typeof ApiInternetRoute
  '/api/memories': typeof ApiMemoriesRouteWithChildren
  '/api/model-settings': typeof ApiModelSettingsRoute
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/system': typeof ApiSystemRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/memories/$id': typeof ApiMemoriesIdRoute
  '/api/models/pull': typeof ApiModelsPullRoute
  '/api/conversations/$id/documents': typeof ApiConversationsIdDocumentsRouteWithChildren
  '/api/conversations/$id/documents/$documentId': typeof ApiConversationsIdDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/chat'
    | '/files'
    | '/models'
    | '/settings'
    | '/api/calendar'
    | '/api/chat'
    | '/api/conversations'
    | '/api/document-search'
    | '/api/documents'
    | '/api/internet'
    | '/api/memories'
    | '/api/model-settings'
    | '/api/models'
    | '/api/system'
    | '/api/conversations/$id'
    | '/api/memories/$id'
    | '/api/models/pull'
    | '/api/conversations/$id/documents'
    | '/api/conversations/$id/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/chat'
    | '/files'
    | '/models'
    | '/settings'
    | '/api/calendar'
    | '/api/chat'
    | '/api/conversations'
    | '/api/document-search'
    | '/api/documents'
    | '/api/internet'
    | '/api/memories'
    | '/api/model-settings'
    | '/api/models'
    | '/api/system'
    | '/api/conversations/$id'
    | '/api/memories/$id'
    | '/api/models/pull'
    | '/api/conversations/$id/documents'
    | '/api/conversations/$id/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/chat'
    | '/files'
    | '/models'
    | '/settings'
    | '/api/calendar'
    | '/api/chat'
    | '/api/conversations'
    | '/api/document-search'
    | '/api/documents'
    | '/api/internet'
    | '/api/memories'
    | '/api/model-settings'
    | '/api/models'
    | '/api/system'
    | '/api/conversations/$id'
    | '/api/memories/$id'
    | '/api/models/pull'
    | '/api/conversations/$id/documents'
    | '/api/conversations/$id/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  FilesRoute: typeof FilesRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  ApiCalendarRoute: typeof ApiCalendarRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiDocumentSearchRoute: typeof ApiDocumentSearchRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ApiInternetRoute: typeof ApiInternetRoute
  ApiMemoriesRoute: typeof ApiMemoriesRouteWithChildren
  ApiModelSettingsRoute: typeof ApiModelSettingsRoute
  ApiModelsRoute: typeof ApiModelsRouteWithChildren
  ApiSystemRoute: typeof ApiSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-search': {
      id: '/api/document-search'
      path: '/api/document-search'
      fullPath: '/api/document-search'
      preLoaderRoute: typeof ApiDocumentSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internet': {
      id: '/api/internet'
      path: '/api/internet'
      fullPath: '/api/internet'
      preLoaderRoute: typeof ApiInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories': {
      id: '/api/memories'
      path: '/api/memories'
      fullPath: '/api/memories'
      preLoaderRoute: typeof ApiMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model-settings': {
      id: '/api/model-settings'
      path: '/api/model-settings'
      fullPath: '/api/model-settings'
      preLoaderRoute: typeof ApiModelSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system': {
      id: '/api/system'
      path: '/api/system'
      fullPath: '/api/system'
      preLoaderRoute: typeof ApiSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/memories/$id': {
      id: '/api/memories/$id'
      path: '/$id'
      fullPath: '/api/memories/$id'
      preLoaderRoute: typeof ApiMemoriesIdRouteImport
      parentRoute: typeof ApiMemoriesRoute
    }
    '/api/models/pull': {
      id: '/api/models/pull'
      path: '/pull'
      fullPath: '/api/models/pull'
      preLoaderRoute: typeof ApiModelsPullRouteImport
      parentRoute: typeof ApiModelsRoute
    }
    '/api/conversations/$id/documents': {
      id: '/api/conversations/$id/documents'
      path: '/documents'
      fullPath: '/api/conversations/$id/documents'
      preLoaderRoute: typeof ApiConversationsIdDocumentsRouteImport
      parentRoute: typeof ApiConversationsIdRoute
    }
    '/api/conversations/$id/documents/$documentId': {
      id: '/api/conversations/$id/documents/$documentId'
      path: '/$documentId'
      fullPath: '/api/conversations/$id/documents/$documentId'
      preLoaderRoute: typeof ApiConversationsIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ApiConversationsIdDocumentsRoute
    }
  }
}

interface ApiConversationsIdDocumentsRouteChildren {
  ApiConversationsIdDocumentsDocumentIdRoute: typeof ApiConversationsIdDocumentsDocumentIdRoute
}

const ApiConversationsIdDocumentsRouteChildren: ApiConversationsIdDocumentsRouteChildren =
  {
    ApiConversationsIdDocumentsDocumentIdRoute:
      ApiConversationsIdDocumentsDocumentIdRoute,
  }

const ApiConversationsIdDocumentsRouteWithChildren =
  ApiConversationsIdDocumentsRoute._addFileChildren(
    ApiConversationsIdDocumentsRouteChildren,
  )

interface ApiConversationsIdRouteChildren {
  ApiConversationsIdDocumentsRoute: typeof ApiConversationsIdDocumentsRouteWithChildren
}

const ApiConversationsIdRouteChildren: ApiConversationsIdRouteChildren = {
  ApiConversationsIdDocumentsRoute:
    ApiConversationsIdDocumentsRouteWithChildren,
}

const ApiConversationsIdRouteWithChildren =
  ApiConversationsIdRoute._addFileChildren(ApiConversationsIdRouteChildren)

interface ApiConversationsRouteChildren {
  ApiConversationsIdRoute: typeof ApiConversationsIdRouteWithChildren
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdRoute: ApiConversationsIdRouteWithChildren,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiMemoriesRouteChildren {
  ApiMemoriesIdRoute: typeof ApiMemoriesIdRoute
}

const ApiMemoriesRouteChildren: ApiMemoriesRouteChildren = {
  ApiMemoriesIdRoute: ApiMemoriesIdRoute,
}

const ApiMemoriesRouteWithChildren = ApiMemoriesRoute._addFileChildren(
  ApiMemoriesRouteChildren,
)

interface ApiModelsRouteChildren {
  ApiModelsPullRoute: typeof ApiModelsPullRoute
}

const ApiModelsRouteChildren: ApiModelsRouteChildren = {
  ApiModelsPullRoute: ApiModelsPullRoute,
}

const ApiModelsRouteWithChildren = ApiModelsRoute._addFileChildren(
  ApiModelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  FilesRoute: FilesRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  ApiCalendarRoute: ApiCalendarRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiDocumentSearchRoute: ApiDocumentSearchRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ApiInternetRoute: ApiInternetRoute,
  ApiMemoriesRoute: ApiMemoriesRouteWithChildren,
  ApiModelSettingsRoute: ApiModelSettingsRoute,
  ApiModelsRoute: ApiModelsRouteWithChildren,
  ApiSystemRoute: ApiSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
